"""Bundle rendered hymn SVGs + catalog into the tablet_app's assets.

Usage:
    python3 tablet_app/build_hymns_bundle.py

Reads:
    data/scores/tech_full/*.svg      — 279 tech-rendered hymn scores
    data/hymns/*.json                — titles + keys for the catalog

Writes:
    tablet_app/app/src/main/assets/hymns/<slug>.svg     — 279 SVGs
    tablet_app/app/src/main/assets/harphymnal_hymns.js  — window.HYMN_CATALOG
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCORES = REPO / 'data' / 'scores' / 'tech_full'
HYMNS_JSON = REPO / 'data' / 'hymns'
ASSETS = REPO / 'tablet_app' / 'app' / 'src' / 'main' / 'assets'
HYMNS_OUT = ASSETS / 'hymns'
CATALOG_OUT = ASSETS / 'harphymnal_hymns.js'


def main() -> int:
    if HYMNS_OUT.exists():
        shutil.rmtree(HYMNS_OUT)
    HYMNS_OUT.mkdir(parents=True)

    catalog: list[dict] = []
    svgs = sorted(SCORES.glob('*.svg'))
    for svg in svgs:
        slug = svg.stem
        dest = HYMNS_OUT / svg.name
        shutil.copyfile(svg, dest)
        hymn_json = HYMNS_JSON / f'{slug}.json'
        title = slug.replace('_', ' ').title()
        key_root = ''
        mode = ''
        meter = ''
        if hymn_json.exists():
            try:
                with hymn_json.open('r', encoding='utf-8') as f:
                    data = json.load(f)
                title = data.get('title') or title
                key_root = (data.get('key') or {}).get('root', '')
                mode = (data.get('key') or {}).get('mode', '')
                m = data.get('meter') or {}
                meter = f"{m.get('numerator', '')}/{m.get('denominator', '')}"
            except Exception:
                pass
        catalog.append({
            'slug': slug,
            'title': title,
            'svg': f'hymns/{svg.name}',
            'key': key_root,
            'mode': mode,
            'meter': meter,
        })

    catalog.sort(key=lambda x: x['title'].lower())
    content = (
        '// Auto-generated by tablet_app/build_hymns_bundle.py — do not edit.\n'
        'window.HYMN_CATALOG = '
        + json.dumps(catalog, ensure_ascii=False, indent=2)
        + ';\n'
    )
    CATALOG_OUT.write_text(content, encoding='utf-8')
    print(f'wrote {len(catalog)} hymns to {HYMNS_OUT}')
    print(f'wrote catalog   → {CATALOG_OUT}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
