#!/usr/bin/env python3
"""Generate jazz/reharm_tactics.html from REHARM_TACTICS.md + data/reharm/tactics.json.

Design:
  - REHARM_TACTICS.md  (at repo root) — prose source of intent, rationale,
                                        biases, open questions, process.
  - data/reharm/tactics.json           — structured tactic catalog + biases +
                                        compatibility edges (conflicts, requires).
  - jazz/reharm_tactics.html           — generated view. Never hand-edit.

The HTML has a narrative skeleton baked into this script. The tactic tables
are rendered from the JSON so the pool can evolve without touching the
generator. Prose edits happen in the MD; a human consults the MD directly —
the HTML view repeats the highlights and shows the live tactic catalog.
"""
from __future__ import annotations
import html
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MD_PATH = ROOT / "REHARM_TACTICS.md"
JSON_PATH = ROOT / "data" / "reharm" / "tactics.json"
HTML_PATH = ROOT / "jazz" / "reharm_tactics.html"

# Use the typed schema's validator so build-time warnings match the
# canonical rules (symmetry, requires cycles, derived_from, etc.).
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from trefoil.reharm.schema import TacticsSpec, validate as schema_validate  # noqa: E402


PAGE_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Reharm Tactics — Design Brief</title>
<style>
:root {{
  --bg:#f7f3ea; --ink:#2a2a2a; --muted:#888; --line:#d8d0c0;
  --panel:#ffffff; --banner:#B58900; --accent:#8F6B00;
  --tag-bg:#eee8d5; --code-bg:#f4efe0;
}}
* {{ margin:0; padding:0; box-sizing:border-box; }}
html, body {{ background:var(--bg); color:var(--ink);
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  line-height:1.55; }}
#topbar {{ padding:14px 24px; background:var(--banner); color:#fff;
  display:flex; align-items:baseline; gap:16px; flex-wrap:wrap; }}
#topbar a {{ color:#fff; text-decoration:none; font-size:15px; }}
#topbar h1 {{ font-size:22px; }}
#topbar .sub {{ font-size:13px; opacity:.9; }}
main {{ padding:24px 32px 60px; max-width:1000px; margin:0 auto; }}
h2 {{ color:var(--accent); margin:26px 0 10px 0; font-size:20px;
  border-bottom:1px solid var(--line); padding-bottom:4px; }}
h3 {{ margin:18px 0 6px 0; font-size:16px; color:var(--ink); }}
p {{ margin:8px 0; }}
ul {{ margin:8px 0 12px 22px; }}
li {{ margin:3px 0; }}
.status {{ background:#fff8dc; border:1px solid #e8d898; border-radius:6px;
  padding:10px 14px; margin:16px 0; font-size:14px; }}
.status strong {{ color:var(--accent); }}
code {{ background:var(--code-bg); padding:1px 5px; border-radius:3px;
  font-family:"DejaVu Sans Mono",Consolas,monospace; font-size:0.9em; }}
table.tactics {{ border-collapse:collapse; margin:10px 0 18px 0; width:100%;
  font-size:13.5px; }}
table.tactics th, table.tactics td {{ border:1px solid var(--line);
  padding:6px 10px; text-align:left; vertical-align:top; }}
table.tactics th {{ background:var(--tag-bg); color:var(--accent);
  font-weight:600; }}
table.tactics td.id {{ font-family:"DejaVu Sans Mono",Consolas,monospace;
  font-size:12px; color:var(--muted); white-space:nowrap; }}
.tag {{ display:inline-block; background:var(--tag-bg); color:var(--accent);
  padding:1px 6px; border-radius:10px; font-size:11px; margin-right:3px;
  font-family:"DejaVu Sans Mono",Consolas,monospace; }}
.conflict {{ color:#8b2020; font-size:11px; font-family:monospace; }}
.biases {{ background:var(--panel); border:1px solid var(--line);
  border-radius:6px; padding:12px 16px; margin:12px 0; }}
.biases h3 {{ margin-top:0; }}
.open-q {{ background:#fdf6e3; border:1px solid #e8d898; border-radius:6px;
  padding:12px 16px; margin:12px 0; }}
.toc {{ background:var(--panel); border:1px solid var(--line);
  border-radius:6px; padding:10px 16px; margin:12px 0; font-size:13.5px; }}
.toc a {{ color:var(--accent); text-decoration:none; margin-right:14px; }}
.toc a:hover {{ text-decoration:underline; }}
.note {{ color:var(--muted); font-size:13px; font-style:italic; }}
</style>
</head>
<body>
<div id="topbar">
  <a href="index.html">← Home</a>
  <h1>Reharm Tactics</h1>
  <span class="sub">practice-week exploration assistant · generated from <code>REHARM_TACTICS.md</code> + <code>data/reharm/tactics.json</code></span>
</div>
<main>

<div class="status">
  <strong>Status:</strong> Phase 1 — authoring infrastructure in place.
  Source of truth is <code>REHARM_TACTICS.md</code> at repo root; structured
  pool in <code>data/reharm/tactics.json</code>; this page is generated by
  <code>trefoil/build_reharm_tactics.py</code>.
  <strong>Never hand-edit this HTML.</strong>
</div>

<div class="toc">
  <strong>Jump to:</strong>
  <a href="#goal">Goal</a>
  <a href="#constraints">Constraints</a>
  <a href="#biases">Biases</a>
  <a href="#pool">Tactic pool</a>
  <a href="#open">Open questions</a>
  <a href="#process">Process</a>
</div>

<h2 id="goal">Goal</h2>
<p>A Python tool that models a diatonic jazz harpist preparing Sunday prelude
improvisations on a <strong>47-string lever harp</strong>. Not a real-time
performer — a <strong>practice-week exploration assistant</strong>. Across
the week, the tool generates MIDI + score candidates. The harpist auditions,
curates, and drills favorite fragments. On Sunday, the harpist improvises by
recombining drilled fragments in real time.</p>

<h2 id="constraints">Physical constraints</h2>
<ul>
  <li>47 strings, diatonic, lever-operated (levers raise a string by a semitone).</li>
  <li>Player has 8 fingers (4 per hand, no pinkies).</li>
  <li>Each hand spans ≤ 10 strings (≈ a diatonic 10th).</li>
  <li>Lever flips during performance are expensive: occasional single-bar
      flip-and-back is OK, sustained flips are OK, frequent flipping is not.</li>
  <li>Shapes are pre-curated; the tool selects from them, it does not invent.</li>
  <li>String damping and sympathetic ringing matter to texture.</li>
</ul>

<h2 id="biases">Structural biases</h2>
<div class="biases">
{biases_html}
</div>

<h2 id="pool">Tactic pool</h2>
<p class="note">{n_tactics} tactics across {n_dimensions} dimensions. Hard
conflicts rendered as a red line under each affected tactic. Edit
<code>data/reharm/tactics.json</code> to modify, then re-run
<code>python3 trefoil/build_reharm_tactics.py</code>.</p>

{dimensions_html}

<h2 id="decided">Decisions (resolved scope flags)</h2>
<div class="biases">
<ol>
  <li><strong>Shape library</strong> — optimize for 47-string. Extend <code>pretty_fraction.py</code>: C1..G7, STRING_MIN=1 at C1, STRING_MAX=47 at G7, seven octaves. ≤10-string hand span; <em>gap between hands is flexible</em>.</li>
  <li><strong>v1 activity / texture tactics</strong> — full pool is selectable. No walking-skeleton subset; build the foundation so every tactic in <code>tactics.json</code> is renderable by the MIDI + score pipeline.</li>
  <li><strong>Fragment length</strong> — phrase-aligned, using the phrase boundaries already computed by the parser (<code>data/hymns/&lt;slug&gt;.json → phrases[]</code>).</li>
  <li><strong>Shape count</strong> — "300+" stands as the output expectation of the 47-string extension across qualities × registers.</li>
</ol>
</div>

<h2 id="open">Open questions</h2>
<div class="open-q">
<p>Still unresolved; tracked in <code>REHARM_TACTICS.md</code>:</p>
<ol start="5">
  <li>Verse differentiation — identical per verse, or varied (register/texture intensification)?</li>
  <li>Intro / outro handling — separate artifacts or a <code>phrase_role</code> value?</li>
  <li>Quotation / allusion — in scope?</li>
  <li>Session-level memory across multiple preludes in one service.</li>
  <li>Liturgical mood parameter — Lent restrained, Easter celebratory.</li>
  <li>Per-hymn deny-list for inappropriate treatments.</li>
</ol>
</div>

<h2 id="process">Process</h2>
<ol>
  <li>Edit prose in <code>REHARM_TACTICS.md</code> for intent / rationale changes.</li>
  <li>Edit <code>data/reharm/tactics.json</code> for adding / removing /
      modifying tactic records or compatibility edges.</li>
  <li>Regenerate: <code>python3 trefoil/build_reharm_tactics.py</code>.</li>
  <li>Commit MD + JSON + HTML together.</li>
</ol>
<p class="note">A tactic that doesn't survive contact with real hymn data
gets redefined, flagged <code>rare</code>, or removed — with the reason
recorded in its record's <code>note</code> field.</p>

</main>
</body>
</html>
"""


def render_bias(b: dict) -> str:
    rule = html.escape(b.get("rule", ""))
    name = html.escape(b.get("name", b.get("id", "")))
    target = html.escape(b.get("penalty_target", ""))
    return (
        f'<h3>{name}</h3>\n'
        f'<p>{rule}</p>\n'
        + (f'<p class="note">penalty target: {target}</p>\n' if target else "")
    )


def render_tactic_table(tactics: list[dict]) -> str:
    rows = []
    for t in tactics:
        tags = " ".join(
            f'<span class="tag">{html.escape(tg)}</span>'
            for tg in t.get("tags", [])
        )
        conflicts = t.get("conflicts") or []
        conflict_line = ""
        if conflicts:
            conflict_line = (
                f'<div class="conflict">conflicts: '
                f'{", ".join(html.escape(c) for c in conflicts)}</div>'
            )
        rows.append(
            f'<tr>'
            f'<td class="id">{html.escape(t["id"])}</td>'
            f'<td><strong>{html.escape(t["name"])}</strong>{conflict_line}</td>'
            f'<td>{tags}</td>'
            f'</tr>'
        )
    return (
        '<table class="tactics">\n'
        '<tr><th>id</th><th>tactic</th><th>tags</th></tr>\n'
        + "\n".join(rows)
        + "\n</table>"
    )


def render_dimension(dim: dict, tactics: list[dict]) -> str:
    dim_id = dim["id"]
    name = html.escape(dim["name"])
    return (
        f'<h3 id="dim-{html.escape(dim_id)}">{name} '
        f'<span class="note">({len(tactics)} tactics · <code>{html.escape(dim_id)}</code>)</span></h3>\n'
        + render_tactic_table(tactics)
    )


def build_html(spec: dict) -> str:
    biases_html = "\n".join(render_bias(b) for b in spec.get("biases", []))

    tactics_by_dim: dict[str, list[dict]] = defaultdict(list)
    for t in spec.get("tactics", []):
        tactics_by_dim[t["dimension"]].append(t)

    dim_sections = []
    for dim in spec.get("dimensions", []):
        ts = tactics_by_dim.get(dim["id"], [])
        dim_sections.append(render_dimension(dim, ts))
    dimensions_html = "\n".join(dim_sections)

    return PAGE_TPL.format(
        biases_html=biases_html,
        dimensions_html=dimensions_html,
        n_tactics=len(spec.get("tactics", [])),
        n_dimensions=len(spec.get("dimensions", [])),
    )


def validate(spec: dict) -> list[str]:
    """Return list of validation warnings; empty means clean.

    Thin wrapper that delegates to the typed schema's validator so the
    generator picks up the richer rules (conflict symmetry, requires
    cycles, derived_from targets) without duplicating logic.
    """
    return schema_validate(TacticsSpec.from_dict(spec))


def main():
    spec = json.loads(JSON_PATH.read_text())
    warnings = validate(spec)
    for w in warnings:
        print(f"  WARN: {w}")
    html_out = build_html(spec)
    HTML_PATH.write_text(html_out)
    print(f"wrote {HTML_PATH}")
    print(f"  {len(spec.get('tactics', []))} tactics · "
          f"{len(spec.get('dimensions', []))} dimensions · "
          f"{len(spec.get('biases', []))} biases · "
          f"{len(warnings)} warnings")


if __name__ == "__main__":
    main()
