"""Generate page1.tex for the handout from data/trefoil/page1_chords.json.

Foundational script for the refactor: all future edits to handout page 1
(add patterns, rename chords, re-color, etc.) happen via the JSON data,
and page1.tex is regenerated by this script.  Grammar production used:

    chord_cell = numeral, [ quality ], [ inversion ], { addition }, { omission }

Where numeral, quality follow GRAMMAR.md's `legacy` production, and
inversion / additions / omissions are the new columnar-colored + sub/sup
extensions rendered by the `\\invc{col}{N}`, `\\add{N}`, `\\no{N}` macros
defined in handout.tex's preamble.

Usage:
    python3 -m trefoil.build_page1              # writes page1.tex
    python3 -m trefoil.build_page1 --validate   # check grammar, no write
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "data" / "trefoil" / "page1_chords.json"
OUT_TEX = REPO_ROOT / "page1.tex"
OUT_MD = REPO_ROOT / "page1.md"
OUT_TXT = REPO_ROOT / "page1.txt"

# Unicode rendering tables
CIRCLED = {1: "❶", 2: "❷", 3: "❸", 4: "❹", 5: "❺", 6: "❻", 7: "❼"}
SUPER = str.maketrans("0123456789", "⁰¹²³⁴⁵⁶⁷⁸⁹")
SUB = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉")
ROMAN_UNICODE = {
    "I": "Ⅰ", "II": "Ⅱ", "III": "Ⅲ", "IV": "Ⅳ", "V": "Ⅴ", "VI": "Ⅵ", "VII": "Ⅶ",
    "i": "ⅰ", "ii": "ⅱ", "iii": "ⅲ", "iv": "ⅳ", "v": "ⅴ", "vi": "ⅵ", "vii": "ⅶ",
}


# ─────────────────────────── Rendering ───────────────────────────
# A chord cell produces three renderings depending on output context:
#   unicode  →  markdown / console display (uses ⁰¹²³ / ₀₁₂₃ / ❶❷❸)
#   ascii    →  plain text, emails, commit messages (uses ^ _ markers)
#   latex    →  PDF via pdflatex (uses \rn \add \no \invc macros)

def render_cell_unicode(cell: dict | None) -> str:
    """Markdown/console: real Unicode sub/super chars + circled inversions + roman glyphs."""
    if cell is None:
        return "—"
    num_raw = cell.get("numeral", "")
    # split trailing ° off numeral for roman lookup
    suffix = ""
    num_base = num_raw
    if num_raw.endswith("°"):
        num_base = num_raw[:-1]
        suffix = "°"
    num = ROMAN_UNICODE.get(num_base, num_base) + suffix
    q = cell.get("quality", "") or ""
    out = num + q
    # additions: inline digits
    for a in cell.get("additions", []):
        out += str(a)
    # inversion: Unicode superscript
    inv = cell.get("inversion")
    if inv is not None:
        out += str(inv).translate(SUPER)
    # omissions: Unicode subscript
    for o in cell.get("omissions", []):
        out += str(o).translate(SUB)
    return out


def _asciify(s: str) -> str:
    """Substitute non-ASCII glyphs used in numerals/qualities.
    ° → o (diminished) · ø → h (half-diminished) · Δ → maj"""
    return s.replace("°", "o").replace("ø", "h").replace("Δ", "maj")


def render_cell_ascii(cell: dict | None) -> str:
    """Plain text:
      - additions: inline digits, comma-separated if ANY is ≥10 (to disambiguate)
      - inversion: ^N
      - omissions: single _ consumes all single-digit omissions (e.g. _35 = no 3, no 5)
      - o = diminished, h = half-diminished
      - s consumes exactly ONE digit (s2, s4)
    """
    if cell is None:
        return "--"
    num = _asciify(cell.get("numeral", ""))
    q = _asciify(cell.get("quality", "") or "")
    out = num + q
    adds = cell.get("additions", [])
    if adds:
        if any(a >= 10 for a in adds):
            out += ",".join(str(a) for a in adds)
        else:
            out += "".join(str(a) for a in adds)
    inv = cell.get("inversion")
    if inv is not None:
        out += f"^{inv}"
    omits = cell.get("omissions", [])
    if omits:
        out += "_" + "".join(str(o) for o in omits)
    return out


def render_cell_latex(cell: dict | None, col: int) -> str:
    """LaTeX: \\rn{num}{quality} + \\add{N} + \\invc{col}{N} + \\no{N}."""
    if cell is None:
        return r"\nd"
    num = cell.get("numeral", "")
    q = cell.get("quality") or ""
    # split trailing ° off numeral (for \rn's argument structure)
    if num.endswith("°"):
        base_num = num[:-1]
        q = "°" + q if q else "°"
    else:
        base_num = num
    out = f"\\rn{{{base_num}}}{{{q}}}"
    for a in cell.get("additions", []):
        out += f"\\add{{{a}}}"
    inv = cell.get("inversion")
    if inv is not None:
        out += f"\\invc{{{col}}}{{{inv}}}"
    for o in cell.get("omissions", []):
        out += f"\\no{{{o}}}"
    return out

VALID_NUMERALS = {"I", "ii", "iii", "IV", "V", "vi", "vii", "vii°",
                  "i", "ii°", "iii°", "III", "iv", "v", "vi°", "VI", "VII",
                  "i°", "♭II", "♭III", "♭VI", "♭VII"}
VALID_QUALITIES = {"Δ", "Δ7", "7", "ø7", "°7", "h7", "6", "9",
                   "s2", "s4", "q", "q7", "+8"}
VALID_INVERSIONS = {1, 2, 3, 4, 5, 6, 7}
VALID_DEGREES = {1, 2, 3, 4, 5, 6, 7}
VALID_ADDITIONS = set(range(1, 16))   # 1..15 (additions up to double octave)


def legacy_of(cell: dict) -> str:
    """Reduce a chord to its legacy form: numeral + quality only.

    Per GRAMMAR.md:  legacy = numeral, [ quality ]
    Ambiguous traditional form — strips inversion, additions, omissions.
    Two different chord shapes can collapse to the same legacy name (this
    is how duplicates like 233/434 both → 'ii7' get detected)."""
    if cell is None:
        return ""
    num = cell.get("numeral", "")
    q = cell.get("quality", "") or ""
    return num + q


def chord_of(cell: dict) -> str:
    """Full chord name: legacy + inversion + additions + omissions.

    Per GRAMMAR.md:  chord = numeral, [quality], [inversion], {additions}, {omissions}
    MUST be unique across the table — each distinct shape deserves a distinct chord name.
    If two cells share a chord string, the notation is too ambiguous."""
    if cell is None:
        return ""
    out = legacy_of(cell)
    for a in cell.get("additions", []):
        out += f"+{a}"
    for o in cell.get("omissions", []):
        out += f"_{o}"
    inv = cell.get("inversion")
    if inv is not None:
        out += f"/{inv}"
    return out


def shape_of(pattern: dict, col: int) -> str:
    """Shape = starting-degree + intervals (e.g. '1.233' = deg 1, stack 2-3-3).
    Uniqueness is automatic: each (pattern, col) cell defines its own shape."""
    return f"{col}.{pattern['pattern']}"


def find_legacy_collisions(data: dict) -> dict[str, list[tuple[str, int]]]:
    """Legacy collisions are ACCEPTABLE — many shapes share a legacy name."""
    groups: dict[str, list] = {}
    for p in data["patterns"]:
        for i, c in enumerate(p["cells"]):
            if c is None:
                continue
            groups.setdefault(legacy_of(c), []).append((p["pattern"], i + 1))
    return {k: v for k, v in groups.items() if len(v) > 1}


def find_chord_collisions(data: dict) -> dict[str, list[tuple[str, int]]]:
    """Chord collisions are BUGS — two shapes should never share a full chord name."""
    groups: dict[str, list] = {}
    for p in data["patterns"]:
        for i, c in enumerate(p["cells"]):
            if c is None:
                continue
            groups.setdefault(chord_of(c), []).append((p["pattern"], i + 1))
    return {k: v for k, v in groups.items() if len(v) > 1}


def find_shape_collisions(data: dict) -> dict[str, list[tuple[str, int]]]:
    """Shape collisions are BUGS — each (pattern, col) must be a distinct shape."""
    groups: dict[str, list] = {}
    for p in data["patterns"]:
        for i, c in enumerate(p["cells"]):
            groups.setdefault(shape_of(p, i + 1), []).append((p["pattern"], i + 1))
    return {k: v for k, v in groups.items() if len(v) > 1}


def validate(data: dict) -> list[str]:
    """Return a list of grammar violations (empty = all good)."""
    errors = []
    pats = data.get("patterns", [])
    if not pats:
        errors.append("no patterns found")
        return errors

    def check_chord_dict(cd, where):
        """Shared checker for main chord and each alternate."""
        num = cd.get("numeral")
        if num and num not in VALID_NUMERALS:
            errors.append(f"{where}: unknown numeral {num!r}")
        q = cd.get("quality")
        if q and q not in VALID_QUALITIES:
            errors.append(f"{where}: unknown quality {q!r}")
        inv = cd.get("inversion")
        if inv is not None and inv not in VALID_INVERSIONS:
            errors.append(f"{where}: inversion must be 1..7, got {inv}")
        for a in cd.get("additions", []):
            if a not in VALID_ADDITIONS:
                errors.append(f"{where}: addition {a} not in 1..15")
        for o in cd.get("omissions", []):
            if o not in VALID_DEGREES:
                errors.append(f"{where}: omission {o} not in 1..7")

    seen_patterns = set()
    for p in pats:
        pat = p.get("pattern")
        if not pat:
            errors.append(f"pattern missing 'pattern' key: {p}")
            continue
        if pat in seen_patterns:
            errors.append(f"duplicate pattern: {pat}")
        seen_patterns.add(pat)

        intervals = p.get("intervals", [])
        if not all(i in (2, 3, 4) for i in intervals):
            errors.append(f"pattern {pat}: intervals must be in {{2,3,4}}, got {intervals}")
        if "".join(str(i) for i in intervals) != pat:
            errors.append(f"pattern {pat}: intervals {intervals} do not match pattern digits")

        cells = p.get("cells", [])
        if len(cells) != 7:
            errors.append(f"pattern {pat}: expected 7 cells, got {len(cells)}")

        for i, cell in enumerate(cells):
            col = i + 1
            if cell is None:
                continue
            check_chord_dict(cell, f"pattern {pat} col {col}")
            # alternates: same schema as main chord, optional `context` tag
            for j, alt in enumerate(cell.get("alternates", [])):
                check_chord_dict(alt, f"pattern {pat} col {col} alternate[{j}]")
    return errors


def render_row(pattern: dict) -> str:
    pat = pattern["pattern"]
    cells = pattern["cells"]
    rendered = [render_cell_latex(c, i + 1) for i, c in enumerate(cells)]
    cells_tex = " & ".join(rendered)
    return f"\\textbf{{{pat}}} & {cells_tex} \\\\"


def render_markdown(data: dict) -> str:
    modes = data["modes"]
    patterns = data["patterns"]
    lines = ["# HarpChords — Hand Shape × Mode Table",
             "",
             f"Generated from `{DATA_FILE.relative_to(REPO_ROOT)}` by `trefoil/build_page1.py`. {len(patterns)} patterns × {len(modes)} modes.",
             ""]
    header = "| pattern | " + " | ".join(f"{m['name']} ({m['col']})" for m in modes) + " |"
    sep = "|" + "---|" * (len(modes) + 1)
    lines.append(header)
    lines.append(sep)
    for p in patterns:
        cells = [render_cell_unicode(c) for c in p["cells"]]
        lines.append(f"| **{p['pattern']}** | " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def _render_fixed_width(data: dict, cell_fn, label: str) -> str:
    """Shared fixed-width table renderer — cell_fn is the per-cell stringifier."""
    modes = data["modes"]
    patterns = data["patterns"]
    col_widths = [3] * len(modes)
    for p in patterns:
        for i, c in enumerate(p["cells"]):
            col_widths[i] = max(col_widths[i], len(cell_fn(c)))
    col_widths = [max(w, len(m["name"])) for w, m in zip(col_widths, modes)]

    lines = [f"HarpChords — {len(patterns)} patterns x {len(modes)} modes ({label})"]
    lines.append("")
    header = f"{'pat':>5}"
    for m, w in zip(modes, col_widths):
        header += f"  {m['name'][:w]:<{w}}"
    lines.append(header)
    subheader = f"{'':>5}"
    for m, w in zip(modes, col_widths):
        subheader += f"  {'(' + str(m['col']) + ')':<{w}}"
    lines.append(subheader)
    lines.append("-" * len(header))
    for p in patterns:
        row = f"{p['pattern']:>5}"
        for i, c in enumerate(p["cells"]):
            row += f"  {cell_fn(c):<{col_widths[i]}}"
        lines.append(row)
    return "\n".join(lines) + "\n"


def render_ascii(data: dict) -> str:
    """Fixed-width plain-text table (^N / _N markers)."""
    return _render_fixed_width(data, render_cell_ascii, "ASCII")


def render_unicode_console(data: dict) -> str:
    """Fixed-width Unicode table (real ⁰¹²³ / ₀₁₂₃ chars)."""
    return _render_fixed_width(data, render_cell_unicode, "Unicode")


def render_table(data: dict) -> str:
    """Build the entire tabular (header + 39 rows) as LaTeX."""
    modes = data["modes"]
    patterns = data["patterns"]

    lines = []
    # column spec: pattern label + 7 colored mode columns
    lines.append(r"\begin{tabular}{@{}>{\bfseries}l")
    for m in modes:
        lines.append(f"  >{{\\columncolor{{mode{m['col']}}}}}w{{c}}{{23mm}}")
    lines.append("}")

    # header row 1: mode names
    cells = [" "]
    for m in modes:
        cells.append(f"\\cellcolor{{hdr{m['col']}}}{{\\color{{white}}\\fontsize{{12}}{{13}}\\selectfont {m['name']}}}")
    lines.append(" & ".join(cells) + r" \\")

    # header row 2: mode numbers
    cells = [r"{\fontsize{14}{16}\selectfont$\looparrowright$\raisebox{0.3ex}{\footnotesize+}}"]
    for m in modes:
        cells.append(f"\\cellcolor{{hdr{m['col']}}}{{\\color{{white}}\\fontsize{{20}}{{22}}\\selectfont\\bfseries {m['col']}}}")
    lines.append(" & ".join(cells) + r" \\")

    # data rows
    for p in patterns:
        lines.append(render_row(p))
        lines.append(r"\hline")

    lines.append(r"\end{tabular}")
    return "\n".join(lines)


HEADER = r"""% page1.tex — GENERATED by trefoil/build_page1.py from data/trefoil/page1_chords.json
% Do not hand-edit this file; edit the JSON and regenerate.
%
% Macros required from handout.tex preamble:
%   \rn{numeral}{quality}   — roman + quality
%   \invc{col}{N}           — circled inversion (color by column)
%   \add{N}                 — superscript added note
%   \no{N}                  — subscript omitted note
%   \nd                     — non-diatonic dash
%   \osf{N}                 — sans-serif figure (quality digits)
%   mode1..mode7, hdr1..hdr7 colors

\setlength{\tabcolsep}{3pt}
\renewcommand{\arraystretch}{1.2}
\fontsize{12}{14}\selectfont
\arrayrulecolor{white}\setlength{\arrayrulewidth}{1pt}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--validate", action="store_true",
                    help="check grammar only; do not write page1.tex")
    ap.add_argument("--data", default=str(DATA_FILE), help="input JSON")
    ap.add_argument("--tex", default=str(OUT_TEX), help="output .tex (PDF)")
    ap.add_argument("--md", default=str(OUT_MD), help="output .md (Unicode)")
    ap.add_argument("--txt", default=str(OUT_TXT), help="output .txt (ASCII)")
    ap.add_argument("--format", choices=["tex", "md", "txt", "all"], default="all",
                    help="which format(s) to emit")
    args = ap.parse_args()

    data = json.loads(Path(args.data).read_text())

    errors = validate(data)
    if errors:
        print("GRAMMAR VIOLATIONS:", file=sys.stderr)
        for e in errors:
            print(f"  • {e}", file=sys.stderr)
        if args.validate:
            sys.exit(1)
        print("⚠ proceeding despite errors", file=sys.stderr)

    if args.validate:
        n_patterns = len(data["patterns"])
        n_filled = sum(1 for p in data["patterns"] for c in p["cells"] if c is not None)
        n_total = sum(len(p["cells"]) for p in data["patterns"])
        print(f"✓ validated {n_patterns} patterns, {n_filled}/{n_total} cells filled")

        # Shape uniqueness — MUST be unique
        sh = find_shape_collisions(data)
        if sh:
            print(f"✗ SHAPE collisions ({len(sh)}) — each (pattern, col) must be unique:")
            for k, v in sorted(sh.items()):
                print(f"    {k!r:<12}  @  {', '.join(f'{p}/col{c}' for p, c in v)}")
        else:
            print("✓ all shapes unique")

        # Chord uniqueness — MUST be unique
        ch = find_chord_collisions(data)
        if ch:
            print(f"✗ CHORD collisions ({len(ch)}) — different shapes must have different chord names:")
            for k, v in sorted(ch.items()):
                print(f"    {k!r:<12}  @  {', '.join(f'{p}/col{c}' for p, c in v)}")
        else:
            print("✓ all filled chord names unique")

        # Legacy collisions — ACCEPTABLE, informational only
        lg = find_legacy_collisions(data)
        if lg:
            print(f"ℹ {len(lg)} legacy-name collision(s) (acceptable — legacy is intentionally ambiguous)")

        # Non-zero exit if any MUST-be-unique rule broken
        if sh or ch:
            sys.exit(1)
        return

    if args.format in ("tex", "all"):
        tex = HEADER + render_table(data) + "\n"
        Path(args.tex).write_text(tex)
        print(f"wrote {args.tex} ({len(tex)} bytes)")

    if args.format in ("md", "all"):
        md = render_markdown(data)
        Path(args.md).write_text(md)
        print(f"wrote {args.md} ({len(md)} bytes)")

    if args.format in ("txt", "all"):
        txt = render_ascii(data)
        Path(args.txt).write_text(txt)
        print(f"wrote {args.txt} ({len(txt)} bytes)")


if __name__ == "__main__":
    main()
