#!/usr/bin/env bash
# Helper script for VS Code ABC tasks (play, render-pdf, export-midi).
# Invoked by .vscode/tasks.json as:
#   wsl.exe --cd <wsl-workspace-path> -- bash .vscode/abc-tasks.sh <action> <relative-file>
# Runs Ubuntu ABC tools and opens results via Windows default handler (cmd.exe interop).
set -euo pipefail

action="${1:?missing action}"
relfile="${2:?missing relative file path}"

# VS Code on Windows passes paths with backslashes; convert to forward slashes.
relfile="${relfile//\\//}"

# Resolve relative to current cwd (which the task sets via wsl.exe --cd).
unixfile="$(realpath -- "$relfile")"
unixdir=$(dirname "$unixfile")
filename=$(basename "$unixfile")
stem="${filename%.*}"

cd "$unixdir"

open_with_default_app() {
    cmd.exe /c start "" "$(wslpath -w "$1" 2>/dev/null || echo "$1")" >/dev/null 2>&1 || true
}

open_in_vscode() {
    local winpath
    winpath=$(wslpath -w "$1" 2>/dev/null || echo "$1")
    cmd.exe /c code -r "$winpath" >/dev/null 2>&1 || true
}

case "$action" in
    play)
        # abc2midi emits one .mid per X: block, named "${stem}N.mid" — generate then play all in sequence.
        abc2midi "$filename" >/dev/null
        shopt -s nullglob
        midis=("${stem}"[0-9]*.mid)
        if [ ${#midis[@]} -eq 0 ]; then
            echo "No MIDI files generated by abc2midi" >&2
            exit 1
        fi
        trap 'rm -f "${midis[@]}"' EXIT
        echo "Playing ${#midis[@]} tune(s) via fluidsynth (Ctrl+C to stop)..."
        fluidsynth -ni /usr/share/sounds/sf2/FluidR3_GM.sf2 "${midis[@]}" 2>/dev/null
        ;;
    render-ps)
        abcm2ps -O preview.ps "$filename" >/dev/null
        echo "Generated preview.ps; opening + auto-triggering PostScript Preview..."
        open_in_vscode preview.ps
        # Wait for VS Code to load + focus preview.ps, then synthesize the
        # Ctrl+Alt+Shift+V keystroke (bound to postscript-preview.sidePreview)
        # via Windows SendKeys. ^=Ctrl  %=Alt  +=Shift. Then send Ctrl+W to
        # close the now-redundant preview.ps editor tab, leaving the side
        # preview pane plus the original .abc editor active.
        sleep 1.2
        powershell.exe -NoProfile -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.SendKeys]::SendWait('^%+v'); Start-Sleep -Milliseconds 1200; [System.Windows.Forms.SendKeys]::SendWait('^k'); Start-Sleep -Milliseconds 100; [System.Windows.Forms.SendKeys]::SendWait('9')" >/dev/null 2>&1 || true
        ;;
    export-midi)
        abc2midi "$filename" -o "${stem}.mid" >/dev/null
        echo "Wrote ${stem}.mid"
        ;;
    *)
        echo "Unknown action: $action (expected: play | render-pdf | export-midi)" >&2
        exit 1
        ;;
esac
